### ISSUE TITLE
引入sdk，启动程序报这个错，不引入没错

### ISSUE THREAD

**Issue by yuanmaio** [allenymt/PrivacySentry#26]
Process: com.shgbit.lawwisdom, PID: 26997
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/OnReceiveContentViewBehavior;
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1530)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1614)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1783)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2617)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2690)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:404)
        at android.app.Dialog.setContentView(Dialog.java:506)
        at com.shgbit.lawwisdom.dialogs.SecretDialog.onCreate(SecretDialog.java:42)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:389)
        at android.app.Dialog.show(Dialog.java:293)
        at com.shgbit.lawwisdom.activitys.SplashActivity.showsecret(SplashActivity.java:201)
        at com.shgbit.lawwisdom.activitys.SplashActivity.init(SplashActivity.java:741)
        at com.shgbit.lawwisdom.activitys.SplashActivity.onCreate(SplashActivity.java:188)
        at android.app.Activity.performCreate(Activity.java:6840)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6358)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.OnReceiveContentViewBehavior" on path: DexPathList[[zip file "/data/app/com.shgbit.lawwisdom-1/base.apk"],nativeLibraryDirectories=[/data/app/com.shgbit.lawwisdom-1/lib/arm, /data/app/com.shgbit.lawwisdom-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1530) 
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1614) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:499) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:430) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1783) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2617) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2690) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:404) 
        at android.app.Dialog.setContentView(Dialog.java:506) 
        at com.shgbit.lawwisdom.dialogs.SecretDialog.onCreate(SecretDialog.java:42) 
        at android.app.Dialog.dispatchOnCreate(Dialog.java:389) 
        at android.app.Dialog.show(Dialog.java:293) 
        at com.shgbit.lawwisdom.activitys.SplashActivity.showsecret(SplashActivity.java:201) 
        at com.shgbit.lawwisdom.activitys.SplashActivity.init(SplashActivity.java:741) 
        at com.shgbit.lawwisdom.activitys.SplashActivity.onCreate(SplashActivity.java:188) 
        at android.app.Activity.performCreate(Activity.java:6840) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6358) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799) 
2022-05-08 23:03:08.354 26997-27016/com.shgbit.lawwisdom E/HMSSDK_HMSPackageManager: Failed to find HMS apk
2022-05-08 23:03:21.295 617-617/? E/cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
    : 00:00:00:00:00:00
2022-05-08 23:03:21.

**Comment by allenymt** [comment]
exclude group: 'androidx.appcompat'
exclude group: 'androidx.core'

在引用hook-sentry和privacy-proxy 把这两个group排掉，可能是版本不一致导致的
