### ISSUE TITLE
报错 Execution failed for task ':app:transformClassesWithPrivacySentryPluginForDebug'. > -1

### ISSUE THREAD

**Issue by duguos330** [allenymt/PrivacySentry#43]
gradle版本
distributionUrl=https://services.gradle.org/distributions/gradle-6.5-all.zip
classpath "com.android.tools.build:gradle:4.1.3"

报错堆栈:
Execution failed for task ':app:transformClassesWithPrivacySentryPluginForDebug'.

-1

Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithPrivacySentryPluginForDebug'.

Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
at org.objectweb.asm.commons.AdviceAdapter.popValue(AdviceAdapter.java:590)
at org.objectweb.asm.commons.AdviceAdapter.visitFieldInsn(AdviceAdapter.java:382)
at com.yl.lib.plugin.sentry.transform.SentryTraceMethodAdapter.visitFieldInsn(HookMethodAsm.kt:138)

     at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210)
at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
at com.yl.lib.plugin.sentry.transform.PrivacyClassProcessor$Companion.runHook(PrivacyClassProcessor.kt:47)
at com.yl.lib.plugin.sentry.transform.PrivacySentryTransform$handleJar$1$2.invoke(PrivacySentryTransform.kt:109)
at com.yl.lib.plugin.sentry.transform.PrivacySentryTransform$handleJar$1$2.invoke(PrivacySentryTransform.kt:15)
at com.yl.lib.plugin.sentry.transform.PrivacyClassProcessor$Companion.processJar(PrivacyClassProcessor.kt:104)
at com.yl.lib.plugin.sentry.transform.PrivacySentryTransform.handleJar(PrivacySentryTransform.kt:104)
at com.yl.lib.plugin.sentry.transform.PrivacySentryTransform.transform(PrivacySentryTransform.kt:53)
at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:281)

**Comment by allenymt** [comment]
有引用高德吗，看下README里的黑名单

**Comment by duguos330** [comment]
> 有引用高德吗，看下README里的黑名单

黑名单配置过了，gradle文件里
![image](https://user-images.githubusercontent.com/42264114/177903921-6780f654-85ad-47fa-950a-2005586942a2.png)

**Comment by duguos330** [comment]
按照之前issue提到的排查方式，日志里查找 jar incremental false file is 有655个结果，不能都加黑名单吧

**Comment by duguos330** [comment]
这个报错解决了，看之前有个issue提到的方式，执行  ./gradlew app:assembleDebug -i  的时候，把异常停止时的包加到黑名单就可以了。这个包是我们自己开发的，后面有类似报错应该都可以这样排查

**Comment by allenymt** [comment]
这个包加了什么~~~~

**Comment by allenymt** [comment]
一直想尝试复现这个问题，都没有场景。

**Comment by duguos330** [comment]
异常触发时的日志：
deal with jar file is: /Users/.../Documents/code/...Android...App/app/build/intermediates/transforms/PrivacyCollectTransform/debug/7.jar.absolutePath entryName is com/.../hitchplatform/widget/AutoSizeViewFlipper$AdapterWrapper.class
deal with jar file is: /Users/.../Documents/code/...Android...App/app/build/intermediates/transforms/PrivacyCollectTransform/debug/7.jar.absolutePath entryName is com/.../hitchplatform/widget/AutoSizeViewFlipper$setAdapter$adapterInternal$1.class
deal with jar file is: /Users/.../Documents/code/...Android...App/app/build/intermediates/transforms/PrivacyCollectTransform/debug/7.jar.absolutePath entryName is com/.../hitchplatform/widget/AutoSizeViewFlipper.class
deal with jar file is: /Users/.../Documents/code/...Android...App/app/build/intermediates/transforms/PrivacyCollectTransform/debug/7.jar.absolutePath entryName is com/.../hitchplatform/widget/ChronometerFormatFix$Companion.class
deal with jar file is: /Users/.../Documents/code/...Android...App/app/build/intermediates/transforms/PrivacyCollectTransform/debug/7.jar.absolutePath entryName is com/.../hitchplatform/widget/ChronometerFormatFix.class
deal with jar file is: /Users/.../Documents/code/...Android...App/app/build/intermediates/transforms/PrivacyCollectTransform/debug/7.jar.absolutePath entryName is com/.../hitchplatform/widget/HitchClearEditText$Companion.class
deal with jar file is: /Users/.../Documents/code/...Android...App/app/build/intermediates/transforms/PrivacyCollectTransform/debug/7.jar.absolutePath entryName is com/.../hitchplatform/widget/HitchClearEditText.class
deal with jar file is: /Users/.../Documents/code/...Android...App/app/build/intermediates/transforms/PrivacyCollectTransform/debug/7.jar.absolutePath entryName is com/.../hitchplatform/widget/HitchTextView.class
deal with jar file is: /Users/.../Documents/code/...Android...App/app/build/intermediates/transforms/PrivacyCollectTransform/debug/7.jar.absolutePath entryName is com/.../hitchplatform/widget/MaxHeightLinearLayout.class
:app:transformClassesWithPrivacySentryPluginForDebug took 71050ms
Task :app:transformClassesWithPrivacySentryPluginForDebug in app Finished

> Task :app:transformClassesWithPrivacySentryPluginForDebug FAILED

最后一个class文件内容：
![image](https://user-images.githubusercontent.com/42264114/177944095-1a3716b2-5787-423c-8c6a-37f1f329ecf0.png)

**Comment by allenymt** [comment]
没什么特殊的
