### ISSUE TITLE
自定义hook的问题

### ISSUE THREAD

**Issue by OhPeterPan** [allenymt/PrivacySentry#64]
不引入 privacy-proxy 这个aar，之后然后自己实现hook方法之后，项目就会闪退，日志如下(看着很像项目以来的广告sdk出现问题):
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yl/lib/privacy_proxy/ProxyProxyField;
        at com.win.opensdk.t1.a(:18)
        at com.win.opensdk.c1.run(:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yl.lib.privacy_proxy.ProxyProxyField" on path: DexPathList[[zip file "/data/app/~~q2h4DQoOQJrg-9EW2bOtgg==/com.mywallpaper.customizechanger-2qfrGhLFeu0izP4yWCxlUA==/base.apk"],nativeLibraryDirectories=[/data/app/~~q2h4DQoOQJrg-9EW2bOtgg==/com.mywallpaper.customizechanger-2qfrGhLFeu0izP4yWCxlUA==/lib/arm64, /data/app/~~q2h4DQoOQJrg-9EW2bOtgg==/com.mywallpaper.customizechanger-2qfrGhLFeu0izP4yWCxlUA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.win.opensdk.t1.a(:18) 
        at com.win.opensdk.c1.run(:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920)

**Comment by OhPeterPan** [comment]
还有就是用 oppo扫描之后发现有些android_id还是无法hook.
[oppo自动化检测报告.xlsx](https://github.com/allenymt/PrivacySentry/files/9392688/iWallart_1.4.6.6_.xlsx)
.

**Comment by allenymt** [comment]
Lcom/yl/lib/privacy_proxy/ProxyProxyField 这个aar是必须依赖的

**Comment by allenymt** [comment]
还有就是用 oppo扫描之后发现有些android_id还是无法hook.

android_id,sdk只是保证进程内只被读取一次，你的问题是定时上传，这个需要你自己处理
