### ISSUE TITLE
appendData这个方法里面用的ArrayList，可能存在多线程问题

### ISSUE THREAD

**Issue by alen252** [allenymt/PrivacySentry#84]
我这边线上统计到一个异常：
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=10; index=10
	at java.util.ArrayList.add(ArrayList.java:468)
	at com.yl.lib.sentry.hook.printer.DefaultFilePrint.appendData(DefaultFilePrint.java:69)
	at com.yl.lib.sentry.hook.printer.BaseFilePrinter.filePrint(BaseFilePrinter.java:23)
	at com.yl.lib.sentry.hook.util.PrivacyProxyUtil$Util.doFilePrinter(PrivacyProxyUtil.java:28)
	at com.yl.lib.sentry.hook.util.PrivacyProxyUtil$Util.doFilePrinter$default$cc7a5ba$2c09eea2(PrivacyProxyUtil.java:12)
	at com.yl.lib.privacy_proxy.PrivacyProxyCall$Proxy.getPackageInfo(PrivacyProxyCall.java:58)

看了下你的源码，感觉可能是多线程引起的

**Comment by runforprogram** [comment]
确实有这个问题，我线上也发现了。

**Comment by allenymt** [comment]
好的 ，下个版本修复

**Comment by allenymt** [comment]
版本号多少的

**Comment by runforprogram** [comment]
1.1.0

**Comment by runforprogram** [comment]
> 版本号多少的

1.1.0

**Comment by allenymt** [comment]
[1.2.1版本已修复](https://github.com/allenymt/PrivacySentry/commit/c98b11c88b6e302cc989c7a8ec5349690d0a1fc8)
